const cron = require('node-cron');
const Product = require('../models/Product');
const PurchaseOrder = require('../models/PurchaseOrder');

class SchedulerService {
  constructor() {
    this.jobs = new Map();
    this.isRunning = false;
  }

  // Start the scheduler
  start() {
    if (this.isRunning) {
      console.log('Scheduler is already running');
      return;
    }

    this.isRunning = true;
    console.log('Starting scheduler service...');

    // Schedule automatic purchase order generation (every hour)
    this.scheduleAutoPurchaseOrders();

    console.log('Scheduler service started successfully');
  }

  // Stop the scheduler
  stop() {
    if (!this.isRunning) {
      console.log('Scheduler is not running');
      return;
    }

    this.jobs.forEach((job, name) => {
      job.destroy();
      console.log(`Stopped job: ${name}`);
    });

    this.jobs.clear();
    this.isRunning = false;
    console.log('Scheduler service stopped');
  }


  // Schedule automatic purchase order generation
  scheduleAutoPurchaseOrders() {
    // Run every hour to check for low stock of raw materials
    const job = cron.schedule('0 * * * *', async () => {
      console.log('Running automatic purchase order generation...');
      await this.generateAutoPurchaseOrders();
    }, {
      scheduled: false,
      timezone: process.env.TIMEZONE || 'UTC'
    });

    this.jobs.set('autoPurchaseOrders', job);
    job.start();
    console.log('Automatic purchase order generation scheduled every hour');
  }


  // Generate automatic purchase orders from low stock
  async generateAutoPurchaseOrders() {
    try {
      // Find RAW MATERIAL products with low stock
      const lowStockProducts = await Product.find({
        $expr: { $lte: ['$currentStock', '$minStockLevel'] },
        category: 'raw-material',
        isActive: true,
        supplier: { $exists: true, $ne: null }
      })
      .populate('supplier', 'name contactPerson email');

      const createdOrders = [];

      for (const product of lowStockProducts) {
        if (!product.supplier) continue;

        // Check if an auto-generated PO already exists for this product in pending status
        const existingOrder = await PurchaseOrder.findOne({
          'items.product': product._id,
          autoGenerated: true,
          status: 'pending'
        });

        if (existingOrder) {
          console.log(`Auto PO already exists for product ${product.name} - skipping`);
          continue;
        }

        const suggestedQuantity = product.maxStockLevel - product.currentStock;
        
        // Generate order number
        const orderCount = await PurchaseOrder.countDocuments();
        const orderNumber = `PO${String(orderCount + createdOrders.length + 1).padStart(4, '0')}`;

        // Calculate totals
        const quantity = Math.max(suggestedQuantity, product.minStockLevel);
        const unitPrice = product.unitCost;
        const total = quantity * unitPrice;
        const subtotal = total;
        const tax = subtotal * 0.1; // 10% tax
        const totalWithTax = subtotal + tax;

        const purchaseOrder = await PurchaseOrder.create({
          orderNumber,
          supplier: product.supplier._id,
          items: [{
            product: product._id,
            quantity,
            unitPrice,
            total
          }],
          subtotal,
          tax,
          total: totalWithTax,
          status: 'pending',
          autoGenerated: true,
          source: 'inventory',
          notes: `Auto-generated from inventory: Current stock ${product.currentStock}, Min level ${product.minStockLevel}`
        });

        await purchaseOrder.populate('supplier', 'name contactPerson email');
        await purchaseOrder.populate('items.product', 'name sku unitCost');

        createdOrders.push(purchaseOrder);
        console.log(`Created auto PO ${orderNumber} for ${product.name}`);
      }

      if (createdOrders.length > 0) {
        console.log(`Successfully created ${createdOrders.length} automatic purchase orders`);
      } else {
        console.log('No new automatic purchase orders needed');
      }
    } catch (error) {
      console.error('Error generating automatic purchase orders:', error);
      // Don't throw error to prevent scheduler from stopping
    }
  }

  // Manually trigger auto purchase order generation
  async triggerAutoPurchaseOrders() {
    console.log('Manually triggering auto purchase order generation...');
    await this.generateAutoPurchaseOrders();
  }

  // Get scheduler status
  getStatus() {
    return {
      isRunning: this.isRunning,
      jobs: Array.from(this.jobs.keys())
    };
  }
}

module.exports = new SchedulerService();
